# Generated by Django 4.2.3 on 2023-07-20 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('91dc825e-0c1b-4da7-aa2b-4a80e4777634'), primary_key=True, serialize=False)),
                ('reposta', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='luiza',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81960bdd-7a7c-43b2-9c6e-d578893c5499'), primary_key=True, serialize=False),
        ),
    ]
