# Generated by Django 4.2.3 on 2023-07-20 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_reposta_resposta_resposta_alter_luiza_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='resposta',
        ),
        migrations.AlterField(
            model_name='luiza',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c30018e-412f-4b3c-ac39-0356cabf08c1'), primary_key=True, serialize=False),
        ),
    ]
